Fix unit test failures (rollover issues) for timed rotations.
Testing under Python 3.13 (there may be other affected versions) I noticed some of the unit tests failing which used time rotation with small intervals. Seemingly because of issues identifying files to delete.

After some back and forth with Claude 3.7 Sonnet and Google Gemini 2.5 Pro, we arrived on this fix. I'm planning to do more review and cleanup.

FAILED tests/test_stresstest.py::test_run_stress_test[backupCount=3, use_gzip=True, use_timed=True, interval=3, log_calls=3_000, num_processes=4-test_opts11]
FAILED tests/test_stresstest.py::test_run_stress_test[backupCount=5, use_timed=True, maxBytes=1KiB, interval=5, log_calls=1_000, use_gzip=True, debug=True-test_opts14]